package com.sandz.mshopping.beans;

import com.sandz.mshopping.dao.DaoSession;
import de.greenrobot.dao.DaoException;


import com.sandz.mshopping.dao.ItemDao;
import com.sandz.mshopping.dao.MonthItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MONTH_ITEMS.
 */
public class MonthItem {

    private Long id;
    /** Not-null value. */
    private java.util.Date month;
    private String comment;
    private Float quantity;
    private Float price;
    private Float discount;
    private Float totalPrice;
    /** Not-null value. */
    private java.util.Date createdOn;
    /** Not-null value. */
    private java.util.Date modifiedOn;
    private Long itemId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MonthItemDao myDao;

    private Item item;
    private Long item__resolvedKey;


    public MonthItem() {
    }

    public MonthItem(Long id) {
        this.id = id;
    }

    public MonthItem(Long id, java.util.Date month, String comment, Float quantity, Float price, Float discount, Float totalPrice, java.util.Date createdOn, java.util.Date modifiedOn, Long itemId) {
        this.id = id;
        this.month = month;
        this.comment = comment;
        this.quantity = quantity;
        this.price = price;
        this.discount = discount;
        this.totalPrice = totalPrice;
        this.createdOn = createdOn;
        this.modifiedOn = modifiedOn;
        this.itemId = itemId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMonthItemDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getMonth() {
        return month;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMonth(java.util.Date month) {
        this.month = month;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Float getDiscount() {
        return discount;
    }

    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    public Float getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /** Not-null value. */
    public java.util.Date getCreatedOn() {
        return createdOn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedOn(java.util.Date createdOn) {
        this.createdOn = createdOn;
    }

    /** Not-null value. */
    public java.util.Date getModifiedOn() {
        return modifiedOn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModifiedOn(java.util.Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /** To-one relationship, resolved on first access. */
    public Item getItem() {
    if (item==null){
          item = new Item();
    }
        return item;
    }

    public void setItem(Item item) {
        synchronized (this) {
            this.item = item;
            itemId = item == null ? null : item.getId();
            item__resolvedKey = itemId;
        }

    }

}
