package com.sandz.mshopping.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sandz.mshopping.beans.Category;
import com.sandz.mshopping.beans.Item;
import com.sandz.mshopping.beans.MonthItem;

import com.sandz.mshopping.dao.CategoryDao;
import com.sandz.mshopping.dao.ItemDao;
import com.sandz.mshopping.dao.MonthItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig monthItemDaoConfig;

    private final CategoryDao categoryDao;
    private final ItemDao itemDao;
    private final MonthItemDao monthItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        monthItemDaoConfig = daoConfigMap.get(MonthItemDao.class).clone();
        monthItemDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        monthItemDao = new MonthItemDao(monthItemDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Item.class, itemDao);
        registerDao(MonthItem.class, monthItemDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        monthItemDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public MonthItemDao getMonthItemDao() {
        return monthItemDao;
    }

}
